version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend:
    image: andreevaa/rs:update
    container_name: backend
    depends_on:
      - postgres
    restart: always
    volumes:
      - ~/lab1/configs/appsettings.json:/app/appsettings.json
    ports:
      - "8080:8080"

volumes:
  db-data:
