name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install requirements
        run: 
          sh install_requirements.sh

      - name: Create app.exe
        run:
          pyinstaller --onefile app.py

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: andreevaa/rs:update
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.VM2_IP }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.VM2_PASSWORD }}
          run: |
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=postgres:13 --format="{{.ID}}"))
            docker stop $(docker ps -q --filter ancestor=andreevaa/rs:update )
            cd rsoi-2023-lab1-ci-cd-AndreevAA
            sudo docker-compose up --build -d

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      # TODO build, test and deploy project

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
